[package]
name = "hello-world"
version = "0.1.0"
authors = ["Thomas Stegmaier <thosteg@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

# The following line:
# for Debian 10 on ARM
#
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
